/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AudioGen": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AvSync": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CodeAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ContentFactoryAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ResearchVisual": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RrqMemory": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "ShortsGen": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Uploader": {
      "name": string
      "type": "sst.aws.Function"
    }
    "VisualGen": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}